# Practice Activity: Text Data - Spam Emails

In this activity you'll work with a small sample from the [Enron email corpus](https://en.wikipedia.org/wiki/Enron_Corpus). The [data set we'll use](https://raw.githubusercontent.com/kevindavisross/data301/refs/heads/main/data/enron_email.csv) contains the subjects and bodies of a sample of e-mails that the Federal Energy Regulatory Commission (FERC) collected during their 2002 investigation of the energy company [Enron](https://en.wikipedia.org/wiki/Enron). Each row in the data set is an email and there are three columns

- subject: the subject of the email
- body: the text of the email
- spam: spam indicator, 1 if spam, 0 if not

For this activity we will only consider the body of the emails (though you could also include the subject using similar methods).

---
title: "Practice Activity: Text Data - Spam Emails"
format:
  html:
    embed-resources: true
jupyter: python3
---

In [3]:
import pandas as pd

pd.DataFrame({
    "a": [1, 2],
    "b": [3, 4]
})

   a  b
0  1  3
1  2  4

In [4]:
import pandas as pd
import numpy as np

1\. The corpus is the body column in the [data set](https://raw.githubusercontent.com/kevindavisross/data301/refs/heads/main/data/enron_email.csv); read this column in to create the corpus.

In [5]:
emails = pd.read_csv(
    "https://raw.githubusercontent.com/kevindavisross/data301/refs/heads/main/data/enron_email.csv")

corpus = emails["body"]

corpus.head()

0    we invoiced mirant americas for deal 705989 an...
1    because the payback was done for october 2001 ...
2    for december 1999 , since the volumes for tran...
3    i would think that the first contract should g...
4    welcome to the aol instant messenger ( sm ) se...
Name: body, dtype: object

2\. Describe in words in detail the steps that you would take to clean the emails and create the term-frequency matrix. We will write the code in the next part, but think carefully first about the process: how do we turn this text into tabular data?

**In order to clean the emails and create a term-frequency matrix, we must start by omitting the empty rows/columns, normalize the data, create tokens by cutting the text into units, then lastly build a vocabulary with a set of the distinct tokens and count them**

3\. Use `CountVectorizer` to create the TF matrix, and then convert it to a pandas data frame with appropriate column names. You can just use the defaults in `CountVectorizer`. Hint: this should pretty much be a straight copy of code from the reading, but make sure you understand the process behind the code.

In [6]:
corpus.str.lower()

0       we invoiced mirant americas for deal 705989 an...
1       because the payback was done for october 2001 ...
2       for december 1999 , since the volumes for tran...
3       i would think that the first contract should g...
4       welcome to the aol instant messenger ( sm ) se...
                              ...
1985    simply visti our site and let ' s see if we ca...
1986    order your medication here - no doctor visit n...
1987    wed , 09 jun 2004 13 : 33 : 18 - 0300\nsir or ...
1988    had chance at last to view the warner bros . l...
1989    while example milk . water , own , make , wire...
Name: body, Length: 1990, dtype: object

In [5]:
emails["body"].isna().sum()

np.int64(61)

In [7]:
corpus = emails["body"].fillna("")
corpus

0       we invoiced mirant americas for deal 705989 an...
1       because the payback was done for october 2001 ...
2       for december 1999 , since the volumes for tran...
3       i would think that the first contract should g...
4       welcome to the aol instant messenger ( sm ) se...
                              ...
1985    simply visti our site and let ' s see if we ca...
1986    order your medication here - no doctor visit n...
1987    wed , 09 jun 2004 13 : 33 : 18 - 0300\nsir or ...
1988    had chance at last to view the warner bros . l...
1989    while example milk . water , own , make , wire...
Name: body, Length: 1990, dtype: object

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()
tf = vec.fit_transform(corpus)
tf_df = pd.DataFrame(tf.toarray(), columns=vec.get_feature_names_out())

In [8]:
tf_df

,00,000,0000,000000,000000000002858,000000000049773,000080,0001,00020608,0004,...,zyban,zykfe,zyl,zynsdirnh,zynve,zyqtaqlt,zyyqywp,zzezrjok,zzo,zzso
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1987,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

4\. Explain what a document frequency (DF) is, and the idea of an IDF. Why might we use TF-IDF rather than just TF? This question is asking about concepts rather than computations.

**A document frequency is the amount of times a given Int64 value appears. IDF gives larger weights to rare words and less weight to more common words. TF-IDF is a combination where the value is high when a word appears a lot in a given email and is rare throughout the entire corpus**

5\. Use `TfidfVectorizer` to create the TF matrix, and then convert it to a pandas data frame with appropriate column names. You can just use the defaults in `TfidfVectorizer`. Hint: this should pretty much be a straight copy of code from the reading, but make sure you understand the process behind the code.

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vec = TfidfVectorizer()
tfidf = tfidf_vec.fit_transform(corpus)
tfidf_df = pd.DataFrame(tfidf.toarray(), columns=tfidf_vec.get_feature_names_out())

In [11]:
tfidf_df

,00,000,0000,000000,000000000002858,000000000049773,000080,0001,00020608,0004,...,zyban,zykfe,zyl,zynsdirnh,zynve,zyqtaqlt,zyyqywp,zzezrjok,zzo,zzso
0,0.0,0.106624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,0.0,0.097060,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
3,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.11587,0.0
1986,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1987,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1988,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1989,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

6\. Remember that the data set also contains an indicator of whether or not the email is spam. In this part you will use descriptive statistics and plots to compare the spam and non-spam emails in terms of their text, represented by the TF and TF-IDF matrices. This part is pretty open ended. First brainstorm some questions or things to investigate, and then write the code to produce relevant summaries.

Note: there are 10 emails for which the spam indicator is missing. You should remove them for this part. We'll come back to them soon.

In [10]:
known = emails["spam"].notna()
spam = emails.loc[known, "spam"]

tf_known = tf_df[known]
tfidf_known = tfidf_df[known]
spam.value_counts()

spam
0.0    995
1.0    985
Name: count, dtype: int64

In [14]:
tf_known.sum(axis=1).groupby(spam).describe().round(1)

      count   mean    std  min   25%   50%    75%     max
spam
0.0   995.0  135.3  181.6  0.0  28.0  74.0  174.5  1833.0
1.0   985.0  176.2  271.3  0.0  36.0  74.0  180.0  2594.0

8\. Consider just one email with unknown spam status, with `loc` 1980. Compute the cosine distance between the TF representation of this email and the TF representation of each of the emails with known spam status.

In [ ]:
from sklearn.metrics.pairwise import cosine_distances

# Emails with known spam status
known_mask = emails["spam"].notna()
known_idx = emails.index[known_mask]

# Email with unknown spam status
target_idx = 1980

distances = cosine_distances(
    tf_df.loc[[target_idx]],
    tf_df.loc[known_idx]).ravel()

results = pd.DataFrame({
    "loc": known_idx,
    "spam": emails.loc[known_idx, "spam"].values,
    "distance": distances})

results.head()

   loc  spam  distance
0    0   0.0  0.736928
1    1   0.0  0.542990
2    2   0.0  0.775802
3    3   0.0  0.653954
4    4   0.0  0.519088

9. Sort the results of the previous part to examine the emails with known spam status that are most similar to the unknown email. If you had to determine if the unknown email was spam or not, which would you pick and why?

In [13]:
results.sort_values("distance").head(10)

       loc  spam  distance
1889  1889   1.0  0.393060
1032  1032   1.0  0.398488
1376  1376   1.0  0.408606
714    714   0.0  0.414644
1110  1110   1.0  0.415807
26      26   0.0  0.418573
180    180   0.0  0.423172
879    879   0.0  0.424620
713    713   0.0  0.427930
139    139   0.0  0.434841

Since the emails with the known lowest cosine distance are spam, I would argue email 1980 is spam. Email 1980 seems to have a similar word frequency pattern to predetermined spam emails

10\. Repeat the two previous parts using TF-IDF instead of TF. Do the results change?

In [15]:
from sklearn.metrics.pairwise import cosine_distances

# Known spam statuses
known_idx = emails.index[emails["spam"].notna()]

# Unknown email we are classifying
target_idx = 1980

distances_tfidf = cosine_distances(
    tfidf_df.loc[[target_idx]],
    tfidf_df.loc[known_idx]).ravel()

results_tfidf = pd.DataFrame({
    "loc": known_idx,
    "spam": emails.loc[known_idx, "spam"].values,
    "distance": distances_tfidf})

results_tfidf = results_tfidf.sort_values("distance")

results_tfidf.head(10)

       loc  spam  distance
1032  1032   1.0  0.755245
1977  1977   1.0  0.780917
48      48   0.0  0.787975
1689  1689   1.0  0.790205
1796  1796   1.0  0.795094
180    180   0.0  0.797415
586    586   0.0  0.798537
1376  1376   1.0  0.799377
279    279   0.0  0.799969
1021  1021   1.0  0.801259

Using TF-IDF does not change our results significantly. Our results show that four of the five emails with the smallest cosine distances are spam, so we still maintain that email 1980 is spam

11\. Now proceed in a similar manner to "guess" the spam status of each of the unknown emails.

In [16]:
# Emails where spam status is known
known_idx = emails.index[emails["spam"].notna()]

# The 10 emails where spam status is unknown
unknown_idx = emails.index[emails["spam"].isna()]

guesses = []

# Repeat the process for each unknown email
for target_idx in unknown_idx:

    distances = cosine_distances(
        tfidf_df.loc[[target_idx]],
        tfidf_df.loc[known_idx]).ravel()

    results = pd.DataFrame({
        "loc": known_idx,
        "spam": emails.loc[known_idx, "spam"].values,
        "distance": distances})

    closest5 = results.sort_values("distance").head(5)

    
    prediction = int(closest5["spam"].mean() > 0.5)

    guesses.append({
        "loc": target_idx,
        "predicted_spam": prediction})

predictions = pd.DataFrame(guesses)

predictions

    loc  predicted_spam
0  1980               1
1  1981               0
2  1982               0
3  1983               0
4  1984               0
5  1985               1
6  1986               1
7  1987               1
8  1988               1
9  1989               0

Emails 1980, 1985-1988 are predicted to be spam. Emails 1981-1984, 1989 are not predicted as spam.